### PR TITLE
Support for 1.1.4, new features

### PR DESCRIPTION
**Pull request by tokkyuruessha**
I intend to pick up development of this project.
This is a part of series of additions i intend to implement.
So far, support for 1.1.4 was introduced('-i' argument for interactive console is deprecated, new start function implemented), as well as Region and Match classes, Find and Highlight functions.

### CODE REVIEW

**Comment by christianrondeau** [comment]
Hi @tokkyuruessha ! Glad to hear that! I'll review, merge and deploy all this asap!

**Comment by christianrondeau** [comment]
Hey @tokkyuruessha ! In general this looks pretty good, but I'll need a little bit more time to merge this. There are a few things I'd like to review first, I'll try to get that done tonight, if I can. Mostly public APIs that I'd like to keep forward compatible (e.g. instead of a 114 boolean, use an enum of supported versions, and eventually allow auto-detect if we can), and avoid the "1.5 fail-safe magic number" if possible. Is there a specific reason why that's there and not in the user code?

I also noticed there was no tests changed; did you try running the automated tests? Otherwise it'll hard for me to confirm this works, and harder for other people to know they didn't break it :) Is this something you'd be comfortable doing? I won't block the PR for that since I'm not actively maintaining it, but I would feel much more comfortable if there was some automated tests for at least the most common operations using the new "dot" method.

**Comment by tokkyuruessha** [comment]
@christianrondeau Sure, there are the "114" functions and bools i just added so i can leave the legacy option untouched. Moing foward they would ideally be merged together. I'm thinking about a way to handle auto-detect. Would doing a File.Exists() on for the jython-standalone binary be a good way perhaps?

I have no clue what the 1.5 magic number is for, mind explaining?

I'm also thinking about a good way to attach the session to objects moving forward. For example, when making regions, store the session so there's no need to use
`session.Click(region);`
but instead just
`region.Click();`

**Comment by tokkyuruessha** [comment]
@RaiMan Is there a way to disable the `RobotDesktop: checkMousePosition` error logging?
I've had setups where I couldn't find a way to avoid them from happening(perhaps some touchpad or mouse or touchscreen driver interfering) and they tend to just clutter logs. It would also benefit in sikulisharp because that's always one message less to process.

**Comment by tokkyuruessha** [comment]
As for the tests, I haven't looked into them yet. I'm not quite familiar with NUnit, so I've just done my own tests so far. I think it's a good idea to have it maintained though.

**Comment by christianrondeau** [comment]
Ok so for now I'll start by making sure that at least current tests are still working with the new version, and will do some refactoring, and report back here. If everything is fine, I'll publish to NuGet, if not I'll let you know. I know many people are waiting for what you've done here, so I'll do my best :)

**Comment by tokkyuruessha** [comment]
Committed one more push. I realized I'v made mistake with the GetTopRight(), GetBottomLeft(), GetBottomRight() functions - they were getting a Location outside the Region.
e.g.
`Region(50,50,50,50).GetBottomRight()`
would point to (100,100) instead of (99,99)
Added some more functions to Region class as well.

**Comment by christianrondeau** [comment]
All right, I tested with 1.1.0 and 1.1.4 and tests pass! The "projects" mode is broken though, and testing for the new features is very limited (I added at least a call to Find and Highlight, but it's just testing that it doesn't crash, it doesn't verify that it works).

If you want to check for .sikuli projects, it might be simple but I don't have more time to spend on this for today. I released 1.5.0 with all changes (they look backward compatible to me) and I also implemented a "version guess" based on which files are in SIKULI_HOME.

If you can check that the NuGet release works with you and your manual tests, I'd feel more comfortable! Thanks!

**Comment by RaiMan** [comment]
@tokkyuruessha 
added an option (latest 1.1.4 build #191):
```
Settings.checkMousePosition = false;
```
will suppress the error message

**Pull request merged**
